### ISSUE TITLE
Errors When Compiling Connector

### ISSUE THREAD

**Issue by bitmage** [infinyon/mqtt-connector#74]
### Errors When Compiling Connector

```
$ git clone git@github.com:infinyon/mqtt-connector.git
$ cd mqtt-connector
$ cdk deploy start --config ../mqtt-to-fluvio.yml
error: could not compile `memchr` (lib) due to 666 previous errors
```

mqtt-to-fluvio.yml
```
# mqtt.yml
apiVersion: 0.1.0
meta:
 version: 0.2.1
 name: fluvio-mqtt-connector
 type: mqtt-source
 topic: mqtt-topic
 direction: source
 create-topic: true
mqtt:
 url: "mqtt://0.0.0.0/"
 topic: "mqtt-to-fluvio"
 timeout:
   secs: 30
   nanos: 0
 payload_output_type: json
```

### Rust Version
I get the same results with both:
```
rustc --version
rustc 1.78.0-nightly (ee9c7c940 2024-02-14)

$ rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)
```

### Fluvio Version
```
 Fluvio CLI                     : 0.11.4                                                           
 Fluvio CLI Arch                : x86_64-unknown-linux-musl                                        
 Fluvio CLI SHA256              : 13ba05c6ef4e37b8c7eb7ea6d703a7cacb5f82fbb31ac28c9b1b617f3884f25b 
 Fluvio Channel Frontend SHA256 : 13ba05c6ef4e37b8c7eb7ea6d703a7cacb5f82fbb31ac28c9b1b617f3884f25b 
 Fluvio Platform                : 0.11.4 (local)                                                   
 Git Commit                     : 45c0089dbcd57123ba27470dd410c7b00b93e2ed                         
 OS Details                     : Manjaro Linux 23.1.3 (kernel 5.10.206-1-MANJARO)
```

### CDK Version

```
 CDK        : 0.11.4                                                           
 CDK Arch   : x86_64-unknown-linux-musl                                        
 CDK SHA256 : 5819115ba1a18be2038c5f01acfdeefbb49f175207acb4e99e536c500c01bf63 
 OS Details : Manjaro Linux 23.1.3 (kernel 5.10.206-1-MANJARO)
```

### Use Case

I'm going through the [MQTT to Postgres](https://www.fluvio.io/docs/tutorials/mqtt-to-sql/) example, but I wanted to see if I could get the components running locally.  Fluvio is running with `fluvio cluster start --local`.  I have a Mosquitto broker and a Postgres instance running in local Docker images, and I can send/receive from both.  My understanding from reading the Fluvio docs is if I want to run a connector locally, I need to compile from source, which brought me here.

I'm not sure if I need a different version of the Rust toolchain, or if there's something else going on.
